version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_django_wx_qhzs
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=django_wx_qhzs
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=E3wWUMKx
      - MYSQL_ADDRESS=10.0.224.10:3306
networks:
  default:
    external:
      name: wxcb0
