# Generated by Django 3.2.13 on 2022-07-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeURL', models.CharField(max_length=60, verbose_name='首页外链')),
                ('homeIMG', models.CharField(max_length=60, verbose_name='图片')),
                ('homeTitle', models.CharField(max_length=60, verbose_name='图片标题')),
                ('animation', models.CharField(max_length=60, verbose_name='首页动画图片')),
            ],
            options={
                'verbose_name': '首页',
                'verbose_name_plural': '首页',
                'db_table': 'sd_homeData',
            },
        ),
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name3', models.CharField(max_length=60, verbose_name='分类')),
            ],
            options={
                'verbose_name': '资讯分类',
                'verbose_name_plural': '资讯分类',
                'db_table': 'sd_newsPosts',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturalLevel', models.CharField(max_length=20, verbose_name='自然级别')),
                ('ParkLevel', models.CharField(max_length=20, verbose_name='行政级别')),
                ('numbering', models.CharField(max_length=20, verbose_name='编号')),
                ('name1', models.CharField(max_length=60, verbose_name='名称')),
                ('fullname', models.CharField(max_length=60, verbose_name='全名')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='简称')),
                ('icon', models.CharField(max_length=60, verbose_name='图标')),
                ('initiate', models.DateTimeField(verbose_name='加入时间')),
                ('slide', models.CharField(max_length=60, verbose_name='轮播图片')),
                ('introduceEN', models.CharField(max_length=600, verbose_name='介绍英')),
                ('introduceZH', models.CharField(max_length=600, verbose_name='介绍中')),
                ('introduceMP3EN', models.CharField(max_length=60, verbose_name='英文语音')),
                ('introduceMP3ZH', models.CharField(max_length=60, verbose_name='中文语音')),
                ('introduceMP4', models.CharField(max_length=60, verbose_name='介绍影片')),
                ('introduceVR', models.CharField(max_length=60, verbose_name='介绍vr')),
                ('lon', models.FloatField(verbose_name='中心经度')),
                ('lat', models.FloatField(verbose_name='中心伟度')),
                ('mapLevel', models.IntegerField(verbose_name='最佳级别')),
                ('province', models.CharField(max_length=10, verbose_name='省')),
                ('area', models.CharField(max_length=20, verbose_name='片区')),
                ('city', models.CharField(max_length=10, verbose_name='市')),
                ('county', models.CharField(max_length=10, verbose_name='县')),
                ('scenery', models.CharField(max_length=20, verbose_name='景点')),
            ],
            options={
                'verbose_name': 'park',
                'verbose_name_plural': 'park',
                'db_table': 'sd_park',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('introduce', models.CharField(max_length=1000, verbose_name='介绍')),
                ('count', models.CharField(max_length=60, verbose_name='数量')),
            ],
            options={
                'verbose_name': '等级',
                'verbose_name_plural': '等级',
                'db_table': 'sd_posts',
            },
        ),
        migrations.CreateModel(
            name='Protect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=60, verbose_name='名称')),
                ('protectURL', models.CharField(max_length=60, verbose_name='外链')),
                ('protectIMG', models.CharField(max_length=60, verbose_name='图片')),
                ('lon', models.FloatField(verbose_name='中心经度')),
                ('lat', models.FloatField(verbose_name='中心伟度')),
                ('fatherPark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.park', verbose_name='所属公园')),
            ],
            options={
                'verbose_name': '公园景点',
                'verbose_name_plural': '公园景点',
                'db_table': 'sd_protect',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMG', models.CharField(max_length=60, verbose_name='图片')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('subTitle', models.CharField(max_length=30, verbose_name='副标题')),
                ('point', models.CharField(max_length=60, verbose_name='要点')),
                ('text', models.CharField(max_length=2000, verbose_name='正文')),
                ('quote', models.CharField(max_length=60, verbose_name='引用位置')),
                ('add_Date', models.DateTimeField(verbose_name='添加时间')),
                ('category', models.CharField(max_length=60, verbose_name='分类')),
                ('fatherPark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.newsposts', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '资讯原文',
                'verbose_name_plural': '资讯原文',
                'db_table': 'sd_news',
            },
        ),
    ]
