# Generated by Django 3.2.13 on 2022-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='abbreviation',
            field=models.CharField(max_length=60, verbose_name='简称'),
        ),
    ]
