# Generated by Django 3.2.13 on 2022-08-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='animation',
            field=models.CharField(max_length=600, verbose_name='首页动画图片'),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='homeIMG',
            field=models.CharField(max_length=600, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='homeTitle',
            field=models.CharField(max_length=600, verbose_name='图片标题'),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='homeURL',
            field=models.CharField(max_length=600, verbose_name='首页外链'),
        ),
        migrations.AlterField(
            model_name='homeimgdata',
            name='homeIMG',
            field=models.CharField(max_length=600, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='homeimgdata',
            name='homeTitle',
            field=models.CharField(max_length=600, verbose_name='图片标题'),
        ),
        migrations.AlterField(
            model_name='homeimgdata',
            name='homeURL',
            field=models.CharField(max_length=600, verbose_name='首页外链'),
        ),
    ]
