# Generated by Django 3.2.13 on 2022-08-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220819_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='homeIMG',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='homeTitle',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='图片标题'),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='homeURL',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='首页外链'),
        ),
    ]
