# Generated by Django 3.2.13 on 2022-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_park_introducemp4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='ParkLevel',
            field=models.CharField(choices=[(1, '国家级自然保护区'), (2, '省级自然保护区'), (3, '国家湿地公园'), (4, '省级湿地公园'), (5, '湿地保护区(小区)'), (6, '省级小微湿地')], max_length=40, verbose_name='级别划分'),
        ),
        migrations.AlterField(
            model_name='park',
            name='area',
            field=models.CharField(choices=[(1, '鄂东北'), (2, '鄂东南'), (3, '鄂西南'), (4, '鄂西北'), (5, '江汉平原')], max_length=40, verbose_name='片区'),
        ),
        migrations.AlterField(
            model_name='park',
            name='city',
            field=models.CharField(choices=[(1, '武汉'), (2, '鄂州'), (3, '黄冈'), (4, '黄石'), (5, '咸宁'), (6, '孝感'), (7, '随州'), (8, '荆门'), (9, '荆州'), (10, '襄阳'), (11, '宜昌'), (12, '十堰'), (13, '恩施'), (14, '神农架'), (15, '天门'), (16, '潜江'), (17, '仙桃')], max_length=20, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='park',
            name='county',
            field=models.CharField(max_length=60, verbose_name='县'),
        ),
        migrations.AlterField(
            model_name='park',
            name='naturalLevel',
            field=models.CharField(choices=[(1, '国际重要湿地'), (2, '国家重要湿地'), (3, '省级重要湿地'), (4, '重要湿地')], max_length=40, verbose_name='自然级别'),
        ),
        migrations.AlterField(
            model_name='park',
            name='numbering',
            field=models.CharField(max_length=40, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='park',
            name='province',
            field=models.CharField(choices=[(1, '湖北省')], max_length=20, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='park',
            name='scenery',
            field=models.CharField(max_length=400, verbose_name='景点'),
        ),
    ]
