# Generated by Django 3.2.13 on 2022-08-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220819_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_Date',
            field=models.CharField(max_length=60, verbose_name='添加时间'),
        ),
    ]
