# Generated by Django 3.2.13 on 2022-09-14 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 9, 14, 15, 39, 41, 136105))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2022, 9, 14, 15, 39, 41, 136105))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
